// ignore_for_file: avoid_print
import 'dart:convert';
import 'dart:io';

/// Merge the SHARED backend-error vocabulary into this app's ARB.
///
/// - `packages/sahra_localization/lib/l10n/app_LOC.arb` (the shared error copy)
/// - `apps/customer_app/lib/localization/source/app_LOC.arb` (screen copy)
/// - merged into `apps/customer_app/lib/localization/app_LOC.arb`, the gen-l10n input
///
/// The shared half exists because both apps show the same backend errors, and
/// two copies of `slot_taken` guarantee two different sentences. The app half
/// exists because doc 07 §2 keeps screen copy in the app.
///
/// Same treatment as tokens.g.dart and the API client: generated, COMMITTED,
/// drift-checked. `--check` diffs instead of writing, so CI fails when someone
/// edits the shared file and forgets this step — and, equally, when someone
/// edits the GENERATED file, which is the mistake that would otherwise silently
/// un-share the shared copy.
void main(List<String> args) {
  final check = args.contains('--check');
  final root = _repoRoot();

  var drifted = false;
  for (final locale in <String>['en', 'ar']) {
    final shared = _read('$root/packages/sahra_localization/lib/l10n/app_$locale.arb');
    final app = _read('$root/apps/customer_app/lib/localization/source/app_$locale.arb');

    final clash = shared.keys.where((k) => !k.startsWith('@') && app.containsKey(k)).toList();
    if (clash.isNotEmpty) {
      // Not a merge conflict to resolve by precedence — a decision to make.
      // Whichever side silently lost would be the one nobody edits again.
      stderr.writeln(
        'Key defined in BOTH the shared vocabulary and this app ($locale): ${clash.join(', ')}\n'
        'Delete one. A silent winner here means editing the loser has no effect.',
      );
      exit(1);
    }

    final merged = <String, dynamic>{
      '@@locale': locale,
      '@@x-generated':
          'GENERATED by tool/merge_arb.dart — do not edit. Screen copy lives in '
              'localization/source/app_$locale.arb; backend error copy lives in '
              'packages/sahra_localization.',
      if (shared['@@x-review-status'] != null || app['@@x-review-status'] != null)
        '@@x-review-status': 'UNREVIEWED',
      ..._without(shared),
      ..._without(app),
    };

    final out = File('$root/apps/customer_app/lib/localization/app_$locale.arb');
    final text = '${const JsonEncoder.withIndent('  ').convert(merged)}\n';

    if (check) {
      final current = out.existsSync() ? out.readAsStringSync() : '';
      if (current != text) {
        drifted = true;
        stderr.writeln(
          '${out.path} is STALE.\n'
          '  Run: dart run tool/merge_arb.dart',
        );
      }
    } else {
      out.writeAsStringSync(text);
      final n = merged.keys.where((k) => !k.startsWith('@')).length;
      print('Wrote ${out.path} — $n keys.');
    }
  }

  if (drifted) exit(1);
  if (check) print('ARB files are current.');
}

/// Strip the `@@`-prefixed metadata, which is per-file and must not be merged.
/// `@key` descriptions ARE kept — they are what a translator reads.
Map<String, dynamic> _without(Map<String, dynamic> arb) =>
    Map<String, dynamic>.fromEntries(arb.entries.where((e) => !e.key.startsWith('@@')));

Map<String, dynamic> _read(String path) {
  final file = File(path);
  if (!file.existsSync()) throw StateError('Missing ARB: $path');
  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

String _repoRoot() {
  var dir = Directory.current;
  for (var i = 0; i < 8; i++) {
    if (Directory('${dir.path}/packages/sahra_localization').existsSync()) return dir.path;
    dir = dir.parent;
  }
  throw StateError('Repo root not found from ${Directory.current.path}');
}
